### ISSUE TITLE
Error in "Edit bridge config" if there are not bridges

### ISSUE THREAD

**Issue by exos** [botmasters/ircgrampp#19]
When open the config wizard:

    ircgrampp config

And select "Edit bridge config" and there are not bridges to edit, this crash with:

```
readline.js:982
            throw err;
            ^

TypeError: Cannot read property 'value' of undefined
    at Prompt.getCurrentValue (/home/exos/alpha/botmasters/ircgrampp/node_modules/inquirer/lib/prompts/list.js:129:51)
    at tryCatcher (/home/exos/alpha/botmasters/ircgrampp/node_modules/rx/dist/rx.js:63:31)
    at InnerObserver.next (/home/exos/alpha/botmasters/ircgrampp/node_modules/rx/dist/rx.js:5407:43)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/home/exos/alpha/botmasters/ircgrampp/node_modules/rx/dist/rx.js:1762:31)
    at InnerObserver.tryCatcher (/home/exos/alpha/botmasters/ircgrampp/node_modules/rx/dist/rx.js:63:31)
    at AutoDetachObserverPrototype.next (/home/exos/alpha/botmasters/ircgrampp/node_modules/rx/dist/rx.js:5883:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/home/exos/alpha/botmasters/ircgrampp/node_modules/rx/dist/rx.js:1762:31)
    at TakeObserver.next (/home/exos/alpha/botmasters/ircgrampp/node_modules/rx/dist/rx.js:5646:17)
    at TakeObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/home/exos/alpha/botmasters/ircgrampp/node_modules/rx/dist/rx.js:1762:31)
    at TakeObserver.tryCatcher (/home/exos/alpha/botmasters/ircgrampp/node_modules/rx/dist/rx.js:63:31)
    at AutoDetachObserverPrototype.next (/home/exos/alpha/botmasters/ircgrampp/node_modules/rx/dist/rx.js:5883:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/home/exos/alpha/botmasters/ircgrampp/node_modules/rx/dist/rx.js:1762:31)
    at Subject.onNext (/home/exos/alpha/botmasters/ircgrampp/node_modules/rx/dist/rx.js:5998:19)
    at Subject.tryCatcher (/home/exos/alpha/botmasters/ircgrampp/node_modules/rx/dist/rx.js:63:31)
    at AutoDetachObserverPrototype.next (/home/exos/alpha/botmasters/ircgrampp/node_modules/rx/dist/rx.js:5883:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/home/exos/alpha/botmasters/ircgrampp/node_modules/rx/dist/rx.js:1762:31)
    at AutoDetachObserver.tryCatcher (/home/exos/alpha/botmasters/ircgrampp/node_modules/rx/dist/rx.js:63:31)
    at AutoDetachObserverPrototype.next (/home/exos/alpha/botmasters/ircgrampp/node_modules/rx/dist/rx.js:5883:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/home/exos/alpha/botmasters/ircgrampp/node_modules/rx/dist/rx.js:1762:31)
    at Interface.handler (/home/exos/alpha/botmasters/ircgrampp/node_modules/rx/dist/rx.async.js:482:11)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:188:7)
```

## Node versions:
* v6.10.0
* v7.10.0

**Comment by exos** [comment]
Fixed
