### ISSUE TITLE
Error when the bot is named in the IRC

### ISSUE THREAD

**Issue by carpe-diem** [botmasters/ircgrampp#22]
If i write in the IRC the bot name, that message not arrive to telegram group

IRC:
`11:57:20 < carpediem> prueba quilmeslug_bot `

bot CLI
```
Unhandled rejection Error: ETELEGRAM: 400 Bad Request: can't parse entities in message text: Can't find end of the entity starting at byte offset 31
    at BaseError (/home/quilmeslug/ircgrampp/node_modules/node-telegram-bot-api/src/errors.js:10:5)
    at TelegramError (/home/quilmeslug/ircgrampp/node_modules/node-telegram-bot-api/src/errors.js:56:5)
    at request.then.err (/home/quilmeslug/ircgrampp/node_modules/node-telegram-bot-api/src/telegram.js:181:15)
    at tryCatcher (/home/quilmeslug/ircgrampp/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/quilmeslug/ircgrampp/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/quilmeslug/ircgrampp/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/quilmeslug/ircgrampp/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/quilmeslug/ircgrampp/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/quilmeslug/ircgrampp/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/quilmeslug/ircgrampp/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/quilmeslug/ircgrampp/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

This error happend in freenode.

Config files:

config.yml
```
channelsdb:          "/home/quilmeslug/.ircgrampp/channels.dat"
telegram: 
  token: "XXXXX"

irc: 
  server: irc.freenode.net
  port:   6697
  nick:   quilmeslug_bot
  secure: true
oneConnectionByUser: false
prefix:              telegram_
showJoinLeft:        false
```

bridges/Quilmeslug.yml 

```
enable:              true
prefix:              telegram_
oneConnectionByUser: false
showJoinLeft:        false
ircScapeCharacter:   "!"
name:                Quilmeslug
telegram: 
  token:   "XXXX"
  channel: QuilmesLug
irc: 
  server:  irc.freenode.net
  port:    6697
  nick:    quilmeslug_bot
  secure:  true
  channel: "#quilmeslug"

```

**Comment by exos** [comment]
This issue is related directly with #20, when you send a IRC message, this isn't escaped and Telegram take the message as markdown, when the markdown format is invalid, the telegram API throws an error.

In this case, when the name of the bot is named, It's not translated as ref, and the name `same_other` open a _ but never close that.
